import Head from "next/head";
// styled components
import { HomePage } from "../styles/home";
// components
import BackgroundHome from "./Background";
import Tasks from "./Tasks";
// redux
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { setTheme } from "../redux/slices/theme";
import { setTasks } from "../redux/slices/tasks";

export default function Home() {
  const theme = useSelector((state) => state.theme.value);
  const dispatch = useDispatch();

  // storage theme in localhost

  useEffect(() => {
    const data = window.localStorage.getItem("theme");
    if (data !== null) {
      dispatch(setTheme(JSON.parse(data)));
    }
  }, []);

  // storage tasks in localStorage

  useEffect(() => {
    const data = localStorage.getItem("tasks");
    if (data !== null) {
      dispatch(setTasks(JSON.parse(data)));
    }
  }, []);

  return (
    <HomePage mode={theme}>
      <Head>
        <title>Todo App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200&display=swap"
          rel="stylesheet"
        />
      </Head>
      <BackgroundHome />
      <Tasks />
    </HomePage>
  );
}
