import Head from "next/head";
// styled components
import { HomePage } from "../styles/home";
// components
import BackgroundHome from "./Background";
import Tasks from "./Tasks";

export default function Home() {
  return (
    <HomePage>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundHome />
      <Tasks />
    </HomePage>
  );
}
