import Head from "next/head";
// styled components
import { HomePage } from "../styles/home";
// components
import BackgroundHome from "./Background";
import Tasks from "./Tasks";
// redux
import { useSelector } from "react-redux";

export default function Home() {
  const theme = useSelector((state) => state.theme.value);
  return (
    <HomePage mode={theme}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200&display=swap"
          rel="stylesheet"
        />
      </Head>
      <BackgroundHome />
      <Tasks />
    </HomePage>
  );
}
